# Generated by Django 4.2.5 on 2026-03-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_rename_updated_at_syncconfig_updatedat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='direction',
            field=models.CharField(choices=[('UPLOAD', 'Local → Online'), ('DOWNLOAD', 'Online → Local')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='local_updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='operation',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('SUCCESS', 'Réussi'), ('FAILED', 'Échoué'), ('CONFLICT', 'Conflit')], default='PENDING', max_length=20, null=True),
        ),
    ]
