# Generated by Django 4.2.5 on 2026-03-06 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_synclog_direction_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='syncconfig',
        #     name='deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='syncconfig',
        #     name='deletedAt',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        migrations.AddField(
            model_name='syncconfig',
            name='last_sync_version',
            field=models.BigIntegerField(default=0),
        ),
        # migrations.AddField(
        #     model_name='syncconfig',
        #     name='sync_version',
        #     field=models.BigIntegerField(default=1),
        # ),
        # migrations.AddField(
        #     model_name='syncconfig',
        #     name='uuid',
        #     field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        # ),
        # migrations.AddField(
        #     model_name='synclog',
        #     name='deleted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='synclog',
        #     name='deletedAt',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='synclog',
        #     name='sync_version',
        #     field=models.BigIntegerField(default=1),
        # ),
        # migrations.AddField(
        #     model_name='synclog',
        #     name='updatedAt',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='synclog',
        #     name='uuid',
        #     field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='syncconfig',
        #     name='createdAt',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='syncconfig',
        #     name='updatedAt',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='synclog',
        #     name='createdAt',
        #     field=models.DateTimeField(auto_now_add=True, null=True),
        # ),
        migrations.AddIndex(
            model_name='syncconfig',
            index=models.Index(fields=['hospital_id'], name='sync_config_hospita_947fa3_idx'),
        ),
    ]
