# Generated by Django 4.2.5 on 2026-03-07 12:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_syncconfig_deleted_syncconfig_deletedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('sync_version', models.BigIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deletedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('model_name', models.CharField(max_length=200)),
                ('hospital_id', models.IntegerField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('UPLOAD', 'UPLOAD'), ('DOWNLOAD', 'DOWNLOAD')], max_length=10)),
                ('objects_data', models.JSONField()),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=5)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
