# Generated by Django 4.2.5 on 2026-03-07 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_syncqueueitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncconfig',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='syncconfig',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='synclog',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='synclog',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncconfig',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
