# Generated by Django 4.2.5 on 2026-03-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0060_archive_deletedat_backupfile_deletedat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='district',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='expenses_nature',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='type_patient',
            name='hospital',
        ),
    ]
