# Generated by Django 4.2.5 on 2026-03-05 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0061_remove_city_hospital_remove_district_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='district',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
