# Generated by Django 4.2.5 on 2026-03-06 12:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0061_remove_city_hospital_remove_district_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('hospital_id', models.IntegerField(blank=True, null=True)),
                ('operation', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('sync_version', models.IntegerField(default=1)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('processedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='detailssupplies',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='archive',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='backupfile',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='cash_movement',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='category',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='city',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='detailsbills',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='detailsinventory',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='detailspatientaccount',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='detailsstock_movement',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='district',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='expenses_nature',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='patientaccount',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='patientsettlement',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='region',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='stock_movement',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='storage_depots',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='type_patient',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='timeAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updateAt',
        ),
        migrations.AddField(
            model_name='archive',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='archive',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='backupfile',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='backupfile',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bills',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cash',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cash',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='cash_movement',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cash_movement',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='categorytranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='cateringinfo',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cateringinfo',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        # migrations.AddField(
        #     model_name='city',
        #     name='hospital',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        # ),
        migrations.AddField(
            model_name='city',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='city',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='composeingredient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='composeingredienttranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='composeingredienttranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='composeingredienttranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='composeingredienttranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='composepreparation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='composepreparation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='composepreparationtranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='composepreparationtranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='composepreparationtranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='composepreparationtranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='deliveryinfo',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailsbills',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailsbills',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailsbillsingredient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailsbillsingredient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailscomposeingredient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailscomposeingredient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailscomposepreparation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailscomposepreparation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailsinventory',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailsinventory',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailspatientaccount',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailspatientaccount',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailsstock_movement',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailsstock_movement',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='detailssupplies',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='detailssupplies',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='dish',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dish',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='dishpreparation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dishpreparation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='dishtranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dishtranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dishtranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dishtranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        # migrations.AddField(
        #     model_name='district',
        #     name='hospital',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        # ),
        migrations.AddField(
            model_name='district',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='district',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventinfo',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='expenses_nature',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expenses_nature',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedgroup',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='extendedpermission',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hospital',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='ingredienttranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredienttranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ingredienttranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredienttranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='insurance',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventory',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='movementstock',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='movementstock',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='patientsettlement',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promotion',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='promotionaction',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promotionaction',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promotionrule',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='promotiontranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='promotiontranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='recipes',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipes',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='region',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='stock_movement',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock_movement',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='storage_depots',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='storage_depots',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='structurearticle',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='structurearticle',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        # migrations.AddField(
        #     model_name='suppliers',
        #     name='is_active',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='suppliers',
        #     name='is_default',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AddField(
            model_name='suppliers',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='supplies',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='supplies',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='type_patient',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='type_patient',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='warehousetranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetranslation',
            name='sync_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehousetranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='warehousetranslation',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='archive',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupfile',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='backupfile',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bills',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='open_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Open Date'),
        ),
        migrations.AlterField(
            model_name='cash_movement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cash_movement',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='cateringinfo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cateringinfo',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='composeingredient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='composeingredient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='composepreparation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='composepreparation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsbills',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsbills',
            name='deletedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsbills',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsbillsingredient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsbillsingredient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailscomposeingredient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailscomposeingredient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailscomposepreparation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsinventory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsinventory',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailspatientaccount',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailspatientaccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsstock_movement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailsstock_movement',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailssupplies',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='dishpreparation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dishpreparation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventinfo',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses_nature',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenses_nature',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='movementstock',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientaccount',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsettlement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientsettlement',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionaction',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotionrule',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotiontranslation',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotiontranslation',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock_movement',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage_depots',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='storage_depots',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='structurearticle',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='structurearticle',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='type_patient',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='type_patient',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.RemoveField(
            model_name='detailssupplies',
            name='timeAt',
        ),
    ]
