# Generated by Django 4.2.5 on 2026-03-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0062_syncqueueitem_alter_detailssupplies_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailssupplies',
            unique_together={('supplies', 'ingredient')},
        ),
    ]
