# Generated by Django 4.2.5 on 2026-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0063_alter_detailssupplies_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suppliers',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
