# Generated by Django 4.2.5 on 2026-03-07 13:33

from django.db import migrations


class Migration(migrations.Migration):
    def add_sync_fields(apps, schema_editor):
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
        models_to_update = [
            "users",
            "bills",
            "cash",
            "categories",
            "city",
            "details_bills",
            "dish",
            "hospital",
            "ingredient",
            "insurance",
            "patient",
            "promotion",
            "suppliers",
            "type_patient",
            "supplies",
            "stock_movement",
            "region",
            "recipe_ingredient",
            "purchase_order",
            "promotion_rule",
            "promotion_action",
            "patient_settlement",
            "patient_account",
            "movement_stock",
            "inventory",
            "extended_permission",
            "extended_group",
            "expenses_nature",
            "event",
            "district",
            "dish_preparation",
            "details_supplies",
            "details_patient_account",
            "details_inventory",
            "details_bills_ingredient",
            "delivery",
            "catering",
            "cash_movement",
            "backup_file",
            "archive",
            "promotion_translation",
            "ingredient_translation",
            "dish_translation",
            "category_translation",
            "recipes",
            "compose_ingredient_translation",
            "deyails_compose_ingredient",
            "compose_ingredient",
            "compose_preparation",
            "details_compose_preparation",
            "compose_preparation_translation",
            "storage_depots",
            "details_stock_movement",
            "warehouse_translation",
            "stock",
            "structure_article",
            "sync_config",
            "sync_log"
        ]

        for table in models_to_update:
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS uuid uuid'
            )
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS sync_version bigint DEFAULT 1'
            )
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS "createdAt" timestamp'
            )
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS "updatedAt" timestamp'
            )
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS deleted boolean DEFAULT false'
            )
            schema_editor.execute(
                f'ALTER TABLE {table} ADD COLUMN IF NOT EXISTS "deletedAt" timestamp'
            )
    def generate_uuid(apps, schema_editor):
        tables = [
            "users",
            "bills",
            "cash",
            "categories",
            "city",
            "details_bills",
            "dish",
            "hospital",
            "ingredient",
            "insurance",
            "patient",
            "promotion",
            "suppliers",
            "type_patient",
            "supplies",
            "stock_movement",
            "region",
            "recipe_ingredient",
            "purchase_order",
            "promotion_rule",
            "promotion_action",
            "patient_settlement",
            "patient_account",
            "movement_stock",
            "inventory",
            "extended_permission",
            "extended_group",
            "expenses_nature",
            "event",
            "district",
            "dish_preparation",
            "details_supplies",
            "details_patient_account",
            "details_inventory",
            "details_bills_ingredient",
            "delivery",
            "catering",
            "cash_movement",
            "backup_file",
            "archive",
            "promotion_translation",
            "ingredient_translation",
            "dish_translation",
            "category_translation",
            "recipes",
            "compose_ingredient_translation",
            "deyails_compose_ingredient",
            "compose_ingredient",
            "compose_preparation",
            "details_compose_preparation",
            "compose_preparation_translation",
            "storage_depots",
            "details_stock_movement",
            "warehouse_translation",
            "stock",
            "structure_article",
            "sync_config",
            "sync_log"
        ]

        for table in tables:
            schema_editor.execute(
                f"UPDATE {table} SET uuid = gen_random_uuid() WHERE uuid IS NULL"
            )
    dependencies = [
        ('hospital', '0063_alter_detailssupplies_unique_together'),
    ]

    operations = [
        migrations.RunPython(add_sync_fields),
        migrations.RunPython(generate_uuid),
    ]
