# Generated by Django 4.2.5 on 2026-03-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0062_city_hospital_district_hospital'),
        ('hospital', '0064_suppliers_is_active_suppliers_is_default'),
        ('hospital', '0065_city_hospital_district_hospital_suppliers_is_active_and_more'),
    ]

    operations = [
    ]
