# Generated by Django 4.2.5 on 2026-03-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0066_merge_20260308_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='hospital',
        ),
    ]
