# Generated by Django 4.2.5 on 2026-03-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0067_remove_city_region_remove_region_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='hospital',
        ),
        migrations.AddField(
            model_name='bills',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='advance_payment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='balance_due',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='company_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='contact_person',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='contract_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bills',
            name='delivery_fee',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='delivery_man',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='delivery_service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='estimated_guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='event_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='event_location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='event_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='event_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bills',
            name='organizer',
            field=models.CharField(max_length=150, null=True),
        )
    ]
